services:
  webui:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/webui.py"

  ranking:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/ranking_client.py"

  trading:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.11
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/trading_client.py"
