services:
  webui:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/webui.py"

  ranking:
    build: .
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/ranking_client.py"

  trading:
    build: .
    volumes:
      - .:/app
      - ./config.py:/app/config.py
    command: >
      sh -c "
      cd /app && git pull && python /app/trading_client.py"
